// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sapovmshrxbthxprlutp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhcG92bXNocnhidGh4cHJsdXRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTk0MzIsImV4cCI6MjA2OTczNTQzMn0.wmfVV7SynCM_UxoAsRbu4NoNLE2pqoVmQZUXWj02kd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});